project:
  type: book
  output-dir: docs

book:
  title: "Humanities Data in Python"
  reader-mode: true
  author: "Taylor Arnold and Lauren Tilton"

  site-url: https://distant-viewing.github.io/hdpy
  repo-url: https://github.com/distant-viewing/hdpy
  repo-branch: main

  page-footer:
    left: |
      Taylor Arnold and Lauren Tilton
    right: |
      A <a href="https://distantviewing.org/">Distant Viewing Lab</a> project

  cover-image: owl_explore.png
  favicon: owl_explore.png

  chapters:
    - index.qmd

    - part: "Part I: Core"
      chapters:
        - 01_intro.qmd
        - 02_graphics.qmd
        - 03_verbs.qmd
        - 04_combine.qmd
        - 05_collect.qmd

    - part: "Part II: Data Types"
      chapters:
        - 06_textual_data.qmd
        - 07_network_data.qmd
        - 08_temporal_data.qmd
        - 09_spatial_data.qmd
        - 10_image_data.qmd
        - 11_audio_data.qmd
        - 12_movingimage_data.qmd

    - part: "Part III: Models"
      chapters:
        - 13_inference.qmd
        - 14_supervised.qmd
        - 15_unsupervised.qmd
        - 16_deeplearning.qmd
        - 17_transformers.qmd

    - part: "Part IV: Programming"
      chapters:
        - 18_program.qmd
        - 19_jsonxml.qmd
        - 20_databases.qmd

bibliography: refs.bib
csl: journal-of-combinatorics.csl

format:
  html:
    theme:
      - cosmo
      - custom.scss

    link-external-newwindow: true
    
    author-meta: "Taylor Arnold and Lauren Tilton"
    callout-appearance: simple
    lightbox: true